# Generated by Django 4.2.7 on 2023-11-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('cel', models.CharField(max_length=15)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.tipodoc')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
