# Generated by Django 4.2.7 on 2023-11-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='name_rs',
        ),
    ]
