# Generated by Django 4.2.7 on 2023-11-19 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductor', '0002_vehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('fecha_hora_partida', models.DateTimeField(blank=True, null=True)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CargaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carga', to='carga.carga')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conductor', to='conductor.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('observacion', models.CharField(max_length=300)),
                ('carga_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carga_vehiculo', to='carga.cargavehiculo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado', to='carga.estadovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(max_length=300)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_carga', to='carga.carga')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado', to='carga.estadocarga')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partida_carga', to='carga.carga')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionLlegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llegada_carga', to='carga.carga')),
            ],
        ),
        migrations.AddField(
            model_name='cargavehiculo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_actual', to='carga.estadovehiculo'),
        ),
        migrations.AddField(
            model_name='cargavehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculo', to='conductor.vehiculo'),
        ),
        migrations.AddField(
            model_name='carga',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='carga.categoriacarga'),
        ),
        migrations.AddField(
            model_name='carga',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clase', to='carga.clasecarga'),
        ),
        migrations.AddField(
            model_name='carga',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carga',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_actual', to='carga.estadocarga'),
        ),
        migrations.AddField(
            model_name='carga',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo', to='carga.tipocarga'),
        ),
    ]
