# Generated by Django 4.2.7 on 2023-11-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_carga_fecha_hora_llegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
