# Generated by Django 4.2.7 on 2023-11-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0003_alter_historialestado_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_carga', to='carga.carga'),
        ),
    ]
