# Generated by Django 4.2.7 on 2023-11-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_alter_historialestado_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='fecha_hora_partida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='direccionllegada',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llegada_carga', to='carga.carga'),
        ),
        migrations.AlterField(
            model_name='direccionpartida',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida_carga', to='carga.carga'),
        ),
    ]
