# Generated by Django 4.2.7 on 2023-11-26 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0005_alter_carga_fecha_hora_partida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionllegada',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_llegada', to='carga.carga'),
        ),
        migrations.AlterField(
            model_name='direccionpartida',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_partida', to='carga.carga'),
        ),
    ]
