# Generated by Django 4.2.7 on 2023-11-26 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0006_alter_direccionllegada_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionllegada',
            name='carga',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_llegada', to='carga.carga'),
        ),
        migrations.AlterField(
            model_name='direccionpartida',
            name='carga',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_partida', to='carga.carga'),
        ),
    ]
