# Generated by Django 4.2.7 on 2023-11-27 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0007_alter_direccionllegada_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargavehiculo',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carga', to='carga.carga'),
        ),
        migrations.DeleteModel(
            name='HistorialVehiculo',
        ),
    ]
