# Generated by Django 4.2.7 on 2023-11-27 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carga', '0009_alter_cargavehiculo_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargavehiculo',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conductor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargavehiculo',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargavehiculo',
            name='lon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
