# Generated by Django 4.2.7 on 2023-12-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0010_alter_cargavehiculo_conductor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('monto_cuota', models.FloatField()),
                ('fecha_hora_registro', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='direccionpartida',
            name='carga',
        ),
        migrations.AddField(
            model_name='carga',
            name='forma_pago',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carga',
            name='llegada',
            field=models.CharField(default='aa', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carga',
            name='partida',
            field=models.CharField(default='aa', max_length=400),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DireccionLlegada',
        ),
        migrations.DeleteModel(
            name='DireccionPartida',
        ),
        migrations.AddField(
            model_name='cuotas',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='carga.carga'),
        ),
    ]
