# Generated by Django 4.2.7 on 2023-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0011_cuotas_remove_direccionpartida_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
    ]
