# Generated by Django 4.2.7 on 2023-11-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customConfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='value',
            new_name='valor',
        ),
    ]
