# Generated by Django 4.2.7 on 2023-11-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=100)),
                ('numero_operacion', models.CharField(max_length=100)),
                ('fecha_hora_operacion', models.DateTimeField()),
                ('voucher', models.CharField(max_length=200)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.carga')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado', to='pago.estadopago')),
            ],
        ),
    ]
