# Generated by Django 4.2.7 on 2023-11-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='voucher',
            field=models.ImageField(upload_to='pago/'),
        ),
    ]
