# Generated by Django 4.2.7 on 2023-11-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_alter_pago_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='voucher',
            field=models.ImageField(upload_to='pago/vouchers/'),
        ),
    ]
